"""add file_id to conversation

Revision ID: 7444731d37ff
Revises: 0e3307826cc1
Create Date: 2025-05-24 10:31:48.700031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7444731d37ff'
down_revision: Union[str, None] = '0e3307826cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_file_id'), 'conversations', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_file_id'), table_name='conversations')
    op.drop_column('conversations', 'file_id')
    # ### end Alembic commands ###
